package com.zhigangzong.service;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ObjectNode;
import com.zhigangzong.dto.ArchiveRequests.*;
import com.zhigangzong.dto.WarningRequests.Policy;
import com.zhigangzong.entity.*;
import com.zhigangzong.exception.BusinessException;
import com.zhigangzong.mapper.*;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.time.*;
import java.util.*;
import java.io.*;
import java.nio.charset.StandardCharsets;
import java.util.zip.*;
@Service @RequiredArgsConstructor @Transactional public class ArchiveService {
 private final PortalService portal; private final PortalMapper accounts; private final PlacementArchiveMapper mapper; private final GradeService grades; private final GradeReviewService reviews; private final GradeReviewMapper reviewHistory; private final GradeMapper evaluationHistory; private final ProcessMapper process; private final AttendanceWorkflowMapper attendance; private final ExtensionMapper changes; private final SelfPlacementMapper self; private final WarningMapper warnings; private final FileMapper fileHistory; private final FileService files; private final ManagementMapper audit; private final StudentProfileMapper students; private final ObjectMapper json;
 private InternshipPlacement accessible(long id,PortalMapper.Actor a){var scope=mapper.scope(id,a.schoolId());if(scope==null)throw BusinessException.notFound("实习记录");warnings.policy(((Number)scope.get("batchId")).longValue());return portal.accessiblePlacement(id,a);}
 private void active(InternshipPlacement p){portal.requireCurrent(p);if(!"APPROVED".equals(p.getSchoolApprovalStatus())||!"ARRIVED".equals(p.getArrivalStatus()))throw BusinessException.badRequest("学校批准且到岗的实习才能结项");}
 private String snapshot(InternshipPlacement p,String summary,long resultId){
  active(p);if(p.getEndDate().isAfter(LocalDate.now(ZoneId.of("Asia/Shanghai"))))throw BusinessException.badRequest("实习尚未结束，不能结项");var calculation=grades.calculate(p);if(!calculation.passed())throw BusinessException.badRequest("成绩未达批次及格线，不能结项");Long reviewed=reviews.approved(p);if(reviewed==null)throw BusinessException.badRequest("当前成绩尚未通过学校复核，不能结项");if(!changes.active(p.getId()).isEmpty())throw BusinessException.badRequest("请先处理实习变更申请");if(mapper.warnings(p.getId())>0)throw BusinessException.badRequest("请先完成本实习预警的处理复核");
  var reports=process.reports(p.getId());if(reports.stream().anyMatch(r->!"REVIEWED".equals(r.getStatus())))throw BusinessException.badRequest("请先完成全部周报的提交和批阅");var attendanceRecords=attendance.records(p.getId());if(attendanceRecords.stream().anyMatch(r->List.of("PENDING","RETURNED").contains(r.getStatus())))throw BusinessException.badRequest("请先处理待审或退回考勤申请");
  var attachments=mapper.files(p.getId());var latest=new LinkedHashMap<String,StoredFile>();for(var f:attachments)latest.put(f.getKind(),f);if(latest.values().stream().anyMatch(f->!"APPROVED".equals(f.getReviewStatus())))throw BusinessException.badRequest("请先审核各类型最新材料");var result=attachments.stream().filter(f->f.getId()==resultId&&"RESULT".equals(f.getKind())&&"APPROVED".equals(f.getReviewStatus())).findFirst().orElseThrow(()->BusinessException.badRequest("请选择本实习已审核通过的成果文件"));if(!Objects.equals(latest.get("RESULT").getId(),result.getId()))throw BusinessException.badRequest("请选择最新审核通过的成果版本");
  String settings=warnings.policy(p.getBatchId());if(settings!=null){try{var policy=json.readValue(settings,Policy.class);if(policy.materials())for(String kind:policy.requiredKinds())if(!latest.containsKey(kind)||!"APPROVED".equals(latest.get(kind).getReviewStatus()))throw BusinessException.badRequest("缺少批次要求的已审核材料："+kind);if(policy.reports())for(var from=p.getStartDate();!from.isAfter(p.getEndDate());from=from.plusDays(policy.frequencyDays())){var to=from.plusDays(policy.frequencyDays()-1);if(to.isAfter(p.getEndDate()))to=p.getEndDate();var start=from;var end=to;if(reports.stream().noneMatch(r->!r.getPeriodStart().isAfter(start)&&!r.getPeriodEnd().isBefore(end)))throw BusinessException.badRequest("缺少已批阅的报告周期："+start+" 至 "+end);}}catch(com.fasterxml.jackson.core.JsonProcessingException ex){throw BusinessException.badRequest("批次过程规则无效");}}
  var data=new LinkedHashMap<String,Object>();ObjectNode placement=json.valueToTree(p);placement.remove(List.of("archiveId","archiveStatus"));data.put("placement",placement);data.put("summary",summary);data.put("resultFileId",resultId);data.put("gradeReviewId",reviewed);data.put("calculation",calculation);data.put("warningPolicy",settings);data.put("approvals",accounts.approvals(p.getId()));data.put("selfDeclaration",self.detail(p.getId()));data.put("selfHistory",self.events(p.getId()));data.put("attendancePolicy",attendance.enabled(p.getId()));data.put("attendancePolicyEvents",attendance.policyEvents(p.getId()));data.put("changes",mapper.changes(p.getId()));data.put("processEvents",process.events(p.getId()));data.put("reports",reports);data.put("attendance",attendanceRecords);data.put("contacts",warnings.contacts(p.getId()));data.put("files",attachments);
  var histories=new LinkedHashMap<String,Object>();for(var r:reports)histories.put("report-"+r.getId(),process.reportEvents(r.getId()));for(var r:attendanceRecords)histories.put("attendance-"+r.getId(),attendance.events(r.getId()));for(var r:calculation.evaluations())histories.put("evaluation-"+r.getId(),evaluationHistory.events(r.getId()));for(var f:attachments)histories.put("file-"+f.getId(),fileHistory.events(f.getId()));for(var r:reviewHistory.list(p.getId()))histories.put("grade-review-"+r.getId(),reviewHistory.events(r.getId()));for(var c:mapper.changes(p.getId()))histories.put("change-"+c.getId(),changes.events(c.getId()));data.put("histories",histories);return grades.write(data);
 }
 public Map<String,Object> view(long id){var a=portal.actor("STUDENT","SCHOOL_ADMIN","TEACHER","ENTERPRISE_MENTOR");var p=accessible(id,a);var r=mapper.lock(id);var result=new LinkedHashMap<String,Object>();result.put("placement",p);if(r!=null){result.put("archive",r);result.put("events",mapper.events(r.getId()));}result.put("resultFiles",mapper.files(id).stream().filter(f->"RESULT".equals(f.getKind())&&"APPROVED".equals(f.getReviewStatus())).toList());return result;}
 public PlacementArchive apply(long id,Apply request){var a=portal.actor("STUDENT");var p=accessible(id,a);active(p);var r=mapper.lock(id);if(r!=null)throw BusinessException.badRequest("已有结项申请，请补充原申请");r=new PlacementArchive();r.setPlacementId(id);r.setResultFileId(request.resultFileId());r.setSummary(request.summary());r.setStatus("PENDING");r.setSnapshot(snapshot(p,r.getSummary(),r.getResultFileId()));mapper.create(r);mapper.event(r,a.id());audit.audit(a.id(),"ARCHIVE_APPLY","placement_archive",r.getId(),r.getSummary());mapper.notifySchool(a.schoolId(),id);return mapper.lock(id);}
 public PlacementArchive resubmit(long id,Apply request){var a=portal.actor("STUDENT");var p=accessible(id,a);active(p);var r=mapper.lock(id);if(r==null||!"RETURNED".equals(r.getStatus()))throw BusinessException.badRequest("仅退回结项申请可补充重提");r.setSummary(request.summary());r.setResultFileId(request.resultFileId());r.setSnapshot(snapshot(p,r.getSummary(),r.getResultFileId()));r.setStatus("PENDING");r.setReviewComment(null);r.setReviewerId(null);mapper.save(r);mapper.event(r,a.id());mapper.notifySchool(a.schoolId(),id);return r;}
 public PlacementArchive review(long id,Review request){var a=portal.actor("SCHOOL_ADMIN");var p=accessible(id,a);active(p);var r=mapper.lock(id);if(r==null||!"PENDING".equals(r.getStatus()))throw BusinessException.badRequest("仅待审结项可处理");if("APPROVED".equals(request.decision())){if(!snapshot(p,r.getSummary(),r.getResultFileId()).equals(r.getSnapshot()))throw BusinessException.badRequest("过程资料或规则已变化，请退回学生核对后重提");r.setArchivedAt(LocalDateTime.now(ZoneId.of("Asia/Shanghai")));}r.setStatus(request.decision());r.setReviewerId(a.id());r.setReviewComment(request.comment());mapper.save(r);mapper.event(r,a.id());audit.audit(a.id(),"ARCHIVE_REVIEW","placement_archive",r.getId(),request.decision()+"："+request.comment());accounts.notifyUser(students.findById(p.getStudentId()).getUserId(),"结项审核结果",request.comment(),"PLACEMENT",id);return r;}
 public byte[] export(long id)throws IOException{var a=portal.actor("STUDENT","SCHOOL_ADMIN");accessible(id,a);var r=mapper.lock(id);if(r==null||!"APPROVED".equals(r.getStatus()))throw BusinessException.badRequest("学校批准结项后才能导出档案");var tree=json.readTree(r.getSnapshot());var out=new ByteArrayOutputStream();long total=r.getSnapshot().getBytes(StandardCharsets.UTF_8).length;try(var zip=new ZipOutputStream(out,StandardCharsets.UTF_8)){entry(zip,"archive.json",r.getSnapshot().getBytes(StandardCharsets.UTF_8));var approval=grades.write(Map.of("archiveId",r.getId(),"reviewerId",r.getReviewerId(),"comment",r.getReviewComment(),"archivedAt",r.getArchivedAt()));total+=approval.getBytes(StandardCharsets.UTF_8).length;entry(zip,"approval.json",approval.getBytes(StandardCharsets.UTF_8));for(var f:tree.path("files")){total+=f.path("byteSize").asLong();if(total>100L*1024*1024)throw BusinessException.badRequest("档案导出最多 100 MB，请分别下载原文件");var downloaded=files.download(f.path("id").asLong(),false);entry(zip,"files/"+downloaded.file().getId()+"-"+downloaded.file().getOriginalName(),downloaded.bytes());}}audit.audit(a.id(),"ARCHIVE_EXPORT","placement_archive",r.getId(),"导出已批准档案及原文件");return out.toByteArray();}
 private void entry(ZipOutputStream zip,String name,byte[] bytes)throws IOException{zip.putNextEntry(new ZipEntry(name));zip.write(bytes);zip.closeEntry();}
}
