package com.zhigangzong.service;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.zhigangzong.dto.GradeRequests.*;
import com.zhigangzong.entity.*;
import com.zhigangzong.exception.BusinessException;
import com.zhigangzong.mapper.*;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.math.*;
import java.util.*;
@Service @RequiredArgsConstructor @Transactional public class GradeService {
 private final PlacementArchiveMapper archives; private final WorkflowPolicyResolver workflow;
 private final PortalService portal; private final PortalMapper accounts; private final GradeMapper mapper; private final WarningMapper warnings; private final StudentProfileMapper students; private final ManagementMapper audit; private final ObjectMapper json;
 public record Calculation(long batchId,int policyVersion,Policy policy,List<EvaluationEntry> evaluations,BigDecimal total,boolean passed,Long workflowPolicyId) {}
 String write(Object o){try{return json.writeValueAsString(o);}catch(JsonProcessingException ex){throw new IllegalStateException(ex);}}
 private Policy policy(String s){try{return json.readValue(s,Policy.class);}catch(JsonProcessingException ex){throw BusinessException.badRequest("评分规则无效，请重新配置");}}
 private void batch(long id,PortalMapper.Actor a){var b=accounts.batch(id);if(b==null||warnings.departmentSchool(b.getDepartmentId())!=a.schoolId())throw BusinessException.notFound("本校批次");}
 public Map<String,Object> settings(long id){var a=portal.actor("SCHOOL_ADMIN");batch(id,a);var result=new LinkedHashMap<String,Object>();var p=mapper.policy(id);if(p!=null){result.put("policy",policy((String)p.get("settings")));result.put("version",p.get("version"));}result.put("events",mapper.policyEvents(id));return result;}
 public Map<String,Object> savePolicy(long id,Policy r){var a=portal.actor("SCHOOL_ADMIN");batch(id,a);if(r.studentWeight().add(r.enterpriseWeight()).add(r.teacherWeight()).compareTo(new BigDecimal("100"))!=0)throw BusinessException.badRequest("三项评分权重必须合计 100%");mapper.savePolicy(id,write(r));mapper.policyEvent(id,a.id());audit.audit(a.id(),"GRADE_POLICY","internship_batch",id,r.note());return settings(id);}
 private void active(InternshipPlacement p){portal.requireCurrent(p);if(!"APPROVED".equals(p.getSchoolApprovalStatus())||!"ARRIVED".equals(p.getArrivalStatus()))throw BusinessException.badRequest("学校批准并到岗后才能办理评价");}
 private String type(PortalMapper.Actor a){return switch(a.role()){case "STUDENT"->"STUDENT";case "TEACHER"->"TEACHER";case "ENTERPRISE_MENTOR"->"ENTERPRISE";default->throw BusinessException.badRequest("管理员不代替三方评分");};}
 private Long expected(InternshipPlacement p,String type){return switch(type){case "STUDENT"->students.findById(p.getStudentId()).getUserId();case "TEACHER"->p.getTeacherId();default->p.getEnterpriseMentorId();};}
 Calculation calculate(InternshipPlacement p){var row=mapper.policy(p.getBatchId());var inherited=row==null?workflow.resolve(p):null;if(row==null && inherited==null)throw BusinessException.badRequest("本批次未配置评分权重与及格线，不能计算总成绩或结项");var policy=row==null?inherited.policy().grading():policy((String)row.get("settings"));var entries=mapper.entries(p.getId());for(String t:List.of("STUDENT","ENTERPRISE","TEACHER"))if(entries.stream().noneMatch(v->t.equals(v.getType())&&"SUBMITTED".equals(v.getStatus())&&Objects.equals(v.getEvaluatorId(),expected(p,t))))throw BusinessException.badRequest("三方当前评价未提交齐，不能计算总成绩");
  BigDecimal total=BigDecimal.ZERO;for(var v:entries){var weight=switch(v.getType()){case "STUDENT"->policy.studentWeight();case "ENTERPRISE"->policy.enterpriseWeight();default->policy.teacherWeight();};total=total.add(v.getScore().multiply(weight).divide(new BigDecimal("100")));}total=total.setScale(2,RoundingMode.HALF_UP);return new Calculation(p.getBatchId(),row==null?inherited.version():((Number)row.get("version")).intValue(),policy,entries,total,total.compareTo(policy.passScore())>=0,row==null?inherited.id():null);
 }
 com.fasterxml.jackson.databind.JsonNode archivedCalculation(InternshipPlacement p){try{return json.readTree(archives.lock(p.getId()).getSnapshot()).path("calculation");}catch(com.fasterxml.jackson.core.JsonProcessingException ex){throw new IllegalStateException(ex);}}
 Long archivedReviewId(InternshipPlacement p){try{return json.readTree(archives.lock(p.getId()).getSnapshot()).path("gradeReviewId").asLong();}catch(com.fasterxml.jackson.core.JsonProcessingException ex){throw new IllegalStateException(ex);}}
 public Map<String,Object> view(long id){var a=portal.actor("STUDENT","SCHOOL_ADMIN","TEACHER","ENTERPRISE_MENTOR");var p=portal.accessiblePlacement(id,a);var result=new LinkedHashMap<String,Object>();result.put("placement",p);result.put("evaluations",mapper.entries(id).stream().filter(v->!"DRAFT".equals(v.getStatus())||Objects.equals(v.getEvaluatorId(),a.id())||"SCHOOL_ADMIN".equals(a.role())).toList());try{result.put("calculation","APPROVED".equals(p.getArchiveStatus())?archivedCalculation(p):calculate(p));}catch(BusinessException ex){result.put("notReady",ex.getMessage());}return result;}
 public Map<String,Object> history(long id,String type){var a=portal.actor("STUDENT","SCHOOL_ADMIN","TEACHER","ENTERPRISE_MENTOR");portal.accessiblePlacement(id,a);var v=mapper.entries(id).stream().filter(e->type.equals(e.getType())).findFirst().orElseThrow(()->BusinessException.notFound("评价"));if("DRAFT".equals(v.getStatus())&&!Objects.equals(v.getEvaluatorId(),a.id())&&!"SCHOOL_ADMIN".equals(a.role()))throw BusinessException.notFound("评价");return Map.of("evaluation",v,"events",mapper.events(v.getId()));}
 public EvaluationEntry save(long id,Evaluation r){var a=portal.actor("STUDENT","TEACHER","ENTERPRISE_MENTOR");var p=portal.accessiblePlacement(id,a);active(p);String t=type(a);var v=mapper.entries(id).stream().filter(e->t.equals(e.getType())).findFirst().orElse(null);if(v!=null&&"SUBMITTED".equals(v.getStatus())&&Objects.equals(v.getEvaluatorId(),a.id()))throw BusinessException.badRequest("已提交评价须学校退回后补充");if(v==null){v=new EvaluationEntry();v.setPlacementId(id);v.setType(t);v.setEvaluatorId(a.id());v.setScore(r.score());v.setComment(r.comment());mapper.create(v);}else{v.setEvaluatorId(a.id());v.setStatus("DRAFT");v.setScore(r.score());v.setComment(r.comment());mapper.save(v);}v=mapper.entries(id).stream().filter(e->t.equals(e.getType())).findFirst().orElseThrow();mapper.event(v.getId(),a.id(),"DRAFT_SAVED",r.comment(),write(v));audit.audit(a.id(),"EVALUATION_DRAFT","evaluation_entry",v.getId(),t);return v;}
 public EvaluationEntry submit(long id){var a=portal.actor("STUDENT","TEACHER","ENTERPRISE_MENTOR");var p=portal.accessiblePlacement(id,a);active(p);String t=type(a);var v=mapper.entries(id).stream().filter(e->t.equals(e.getType())).findFirst().orElseThrow(()->BusinessException.badRequest("请先保存评价草稿"));if(!Objects.equals(v.getEvaluatorId(),a.id())||!List.of("DRAFT","RETURNED").contains(v.getStatus()))throw BusinessException.badRequest("仅本人草稿或退回评价可提交");v.setStatus("SUBMITTED");mapper.save(v);v=mapper.entries(id).stream().filter(e->t.equals(e.getType())).findFirst().orElseThrow();mapper.event(v.getId(),a.id(),"SUBMITTED",v.getComment(),write(v));mapper.notifySchool(a.schoolId(),id);return v;}
}
